# Generated by Django 5.2.6 on 2025-10-28 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='temperature_db',
            fields=[
                ('myid', models.AutoField(primary_key=True, serialize=False)),
                ('sensor_id', models.IntegerField()),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('timestamp', models.DateField()),
            ],
        ),
    ]
